title: Preparing For a Hearing
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: coopermayne@gmail.com
description: Questions and Answer about LAAD
baseurl: ''
url: https://ucla-dog-adj.firebaseapp.com
twitter_username: gustavoquinalha
github_username: gustavoquinalha
color_theme: "#0081ff"
color_text: "#fff"
language: en
markdown: kramdown
permalink: "/:title/"
gems:
- jekyll-paginate
paginate: 5
plugins_dir:
  - jekyll-admin
